spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456789
    database: 1
    lettuce:
      pool:
        min-idle: 1
        max-idle: 10
        max-active: 10
        max-wait: -1ms