server:
  port: 3690

spring:
  datasource:
    username: root
    password: postgres@369^speed
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.188.188:5432/postgres?binaryTransfer=false&forceBinary=false&reWriteBatchedInserts=true&connect_timeout=15
    hikari:
      # 等待连接时间(毫秒)
      connection-timeout: 10000
      validation-timeout: 3000
      # 连接保持空闲状态的最长时间(毫秒)
      idle-timeout: 300000
      login-timeout: 5
      max-lifetime: 360000
      maximum-pool-size: 6
      minimum-idle: 3
      read-only: false
# sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl